version: '3.8'
services:
  app:
    build: .
    image: pddt-backend-img
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      - pddt-network-0
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.development
    cpus: 1
    mem_limit: 512m

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo-container-0
    networks:
      - pddt-network-0
    ports:
      - "27017:27017"
    env_file:
      - .env.mongo
    cpus: 1
    mem_limit: 512m

networks:
  pddt-network-0:
    name: pddt-network-0
    driver: bridge
